# Generated by Django 3.2.3 on 2021-05-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructor',
            name='championships',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='wins',
        ),
        migrations.AddField(
            model_name='constructor',
            name='constructor_wins',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of victories'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='wcc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of championships'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of an F1 driver (Lewis Hamilton, Max Verstappen...)', max_length=50, unique=True, verbose_name='Driver name')),
                ('nationality', models.CharField(max_length=30, verbose_name='Nationality')),
                ('birth', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Release date')),
                ('driver_wins', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of victories')),
                ('wdc', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of championships')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('teams', models.ManyToManyField(help_text='Select the constructor teams the driver has raced for', to='formula1.Constructor')),
            ],
            options={
                'ordering': ['driver_wins', 'name'],
            },
        ),
    ]
