# Generated by Django 3.2.3 on 2021-05-23 16:47

from django.db import migrations, models
import django.db.models.deletion
import formula1.models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0002_auto_20210522_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=formula1.models.poster_path, verbose_name='Poster'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=formula1.models.attachment_path, verbose_name='File')),
                ('type', models.CharField(blank=True, choices=[('audio', 'Audio'), ('image', 'Image'), ('text', 'Text'), ('video', 'Video'), ('other', 'Other')], default='image', help_text='Select allowed attachment type', max_length=5, verbose_name='Attachment type')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula1.driver')),
            ],
            options={
                'ordering': ['-last_update', 'type'],
            },
        ),
    ]
