# Generated by Django 3.2.3 on 2021-05-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0003_auto_20210523_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-driver_wins', 'name']},
        ),
    ]
