# Generated by Django 3.2.3 on 2021-05-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0004_alter_driver_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-last_update']},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='type',
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.IntegerField(help_text='Please enter the the track id respectively to its order in the 2021 calendar (Bahrain - id 1)', primary_key=True, serialize=False, verbose_name='Track id')),
                ('name', models.CharField(help_text='Enter a name of an F1 track (Suzuka, Catalunya...)', max_length=50, unique=True, verbose_name='Track name')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('first_race', models.DateTimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='First race at the track')),
                ('laps', models.IntegerField(default=55, verbose_name='Number of laps')),
                ('winner', models.ForeignKey(blank=True, help_text='Enter the winner of this circuit from this year (2021)', null=True, on_delete=django.db.models.deletion.CASCADE, to='formula1.driver', verbose_name='2021 winner')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
