# Generated by Django 3.2.3 on 2021-05-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0005_auto_20210526_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='first_race',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='First race at the track'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='name',
            field=models.CharField(help_text='Enter a name of an F1 track (Suzuka, Catalunya...)', max_length=70, unique=True, verbose_name='Track name'),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='teams',
        ),
        migrations.AddField(
            model_name='driver',
            name='teams',
            field=models.ForeignKey(default='', help_text='Select the constructor teams the driver has raced for', on_delete=django.db.models.deletion.CASCADE, to='formula1.constructor'),
        ),
    ]
