# Generated by Django 3.2.3 on 2021-05-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0006_auto_20210527_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='teams',
        ),
        migrations.AddField(
            model_name='driver',
            name='teams',
            field=models.ManyToManyField(help_text='Select the constructor teams the driver has raced for', to='formula1.Constructor'),
        ),
    ]
