# Generated by Django 3.2.3 on 2021-06-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0010_alter_driver_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='teams',
        ),
        migrations.AddField(
            model_name='driver',
            name='teams',
            field=models.ManyToManyField(help_text='Select the constructor team the driver has been racing for', to='formula1.Constructor'),
        ),
    ]
