# Generated by Django 3.2.3 on 2021-06-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0012_auto_20210607_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.AlterField(
            model_name='driver',
            name='birth',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Birth'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(help_text='Enter the name of the F1 driver (Lewis Hamilton, Max Verstappen...)', max_length=50, unique=True, verbose_name='Driver name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='teams',
            field=models.ForeignKey(help_text='Select the constructor team the driver has been racing for', on_delete=django.db.models.deletion.CASCADE, to='formula1.constructor'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='attachment',
            order_with_respect_to='driver',
        ),
        migrations.DeleteModel(
            name='Circuit',
        ),
    ]
