# Generated by Django 3.2.3 on 2021-06-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0013_auto_20210612_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='teams',
            field=models.ForeignKey(help_text='Select the constructor team the driver has been racing for', on_delete=django.db.models.deletion.CASCADE, to='formula1.constructor', verbose_name='Team'),
        ),
    ]
