# Generated by Django 3.2.3 on 2021-06-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0014_alter_driver_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Points in 2021'),
        ),
    ]
